[build-system]
requires = ["jupyter_packaging~=0.4.0", "jupyterlab~=2.0", "setuptools>=40.8.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.coverage.run]
source = """
    jupyter_project"""

[tool.coverage.report]
show_missing = on
