#!/usr/bin/env bash
#
# Binder postBuild instructions
#
# Note: binder is launching jupyter server in the code repository folder
# Therefore the `jupyter_notebook_config.json` will be picked automatically
# as server configuration
# 
set -eux
jupyter lab build
cp -f ./binder/jupyter_notebook_config.json .
