#!/usr/bin/env bash
#
# Binder postBuild instructions
#
# Note: binder is launching jupyter server in the code repository folder
# Therefore the `jupyter_notebook_config.json` will be picked automatically
# as server configuration
# 
set -eux
python -m pip install . --ignore-installed --no-deps
# Clean up the folder
jlpm run clean
rm -rf node_modules
jupyter lab build --minimize=True --dev-build=False --debug
cp -f ./binder/jupyter_notebook_config.json .
